version: '3.7'
services:
  mongo:
    image: mongo:4.2.3-bionic
    container_name: mongo
    ports:
      - 27023:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      
    volumes:
      - mongodbVol:/data/db
      - mongoconfig:/data/configdb

volumes:
  mongodbVol:
  mongoconfig:
