version: '3.6'
services:
  mongodb:
    image: mongo:4.2.3-bionic
    container_name: mongodb
    ports:
      - 27023:27017
    environment:
      - MONGO_INITDB_DATABASE=My-Shop
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodbVol:/data/db
      - mongoconfig:/data/configdb
    
volumes:
  mongodbVol:
  mongoconfig: