[
    {
      total: 1000,
      name: "Smartphone X",
      type: "Phone",
      brand: "BrandA",
      image: "https://cdn.tgdd.vn/Products/Images/42/250258/iphone-13-midnight-1-600x600.jpg",
      quantity: 1,
      _id: "1a2b3c4d5e6f",
    },
    {
      total: 400,
      name: "Wireless Headphones",
      type: "Accessory",
      brand: "BrandB",
      image: "https://cdn.tgdd.vn/Products/Images/42/250258/iphone-13-midnight-1-600x600.jpg",
      quantity: 2,
      _id: "7g8h9i0j1k2l",
    },
    {
      total: 1000,
      name: "Smartphone",
      type: "Phone",
      brand: "BrandA",
      image: "phoneA.jpg",
      quantity: 2,
      _id: "p101",
    },
    {
      total: 1200,
      name: "Laptop",
      type: "Laptop",
      brand: "BrandB",
      image: "laptopB.jpg",
      quantity: 1,
      _id: "p102",
    },
    {
      total: 700,
      name: "Camera",
      type: "Camera",
      brand: "BrandC",
      image: "cameraC.jpg",
      quantity: 1,
      _id: "p103",
    },
    {
      total: 600,
      name: "Smart Watch",
      type: "Watch",
      brand: "BrandD",
      image: "watchD.jpg",
      quantity: 2,
      _id: "p104",
    },
    {
      total: 1500,
      name: "Television",
      type: "Television",
      brand: "BrandE",
      image: "tvE.jpg",
      quantity: 1,
      _id: "p105",
    },
    {
      total: 1200,
      name: "Tablet",
      type: "Laptop",
      brand: "BrandF",
      image: "tabletF.jpg",
      quantity: 3,
      _id: "p106",
    },
    {
      total: 1200,
      name: "Gaming Console",
      type: "Television",
      brand: "BrandG",
      image: "consoleG.jpg",
      quantity: 2,
      _id: "p107",
    },
    {
      total: 800,
      name: "Earbuds",
      type: "Phone",
      brand: "BrandH",
      image: "earbudsH.jpg",
      quantity: 4,
      _id: "p108",
    },
    {
      total: 2000,
      name: "Desktop",
      type: "Laptop",
      brand: "BrandI",
      image: "desktopI.jpg",
      quantity: 1,
      _id: "p109",
    },
    {
      total: 1200,
      name: "Monitor",
      type: "Television",
      brand: "BrandJ",
      image: "monitorJ.jpg",
      quantity: 3,
      _id: "p110",
    },
  ]